version: '3'

vars:
  BINARY_NAME: edge-proxy
  TARGET_DIR: ./target
  RELEASE_BIN: "{{.TARGET_DIR}}/release/{{.BINARY_NAME}}"
  DEBUG_BIN: "{{.TARGET_DIR}}/debug/{{.BINARY_NAME}}"

env:
  RUST_BACKTRACE: 1
  RUST_LOG: info

includes:
  build: .tasks/build.yaml
  test: .tasks/test.yaml
  run: .tasks/run.yaml
  db: .tasks/db.yaml
  node: .tasks/node.yaml
  dev: .tasks/dev.yaml
  deps: .tasks/deps.yaml
  docs: .tasks/docs.yaml
  local: .tasks/local.yaml
  simulation: .tasks/simulation.yaml
  docker: .tasks/docker.yaml
  flyio: .tasks/flyio.yaml
  aws: .tasks/aws.yaml
  gcp: .tasks/gcp.yaml

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list
