version: '3'

vars:
  BINARY_NAME: edge-proxy
  TARGET_DIR: ./target
  RELEASE_BIN: "{{.TARGET_DIR}}/release/{{.BINARY_NAME}}"
  DEBUG_BIN: "{{.TARGET_DIR}}/debug/{{.BINARY_NAME}}"

env:
  RUST_BACKTRACE: 1
  RUST_LOG: info

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  # ============================================
  # Build Tasks
  # ============================================

  build:
    desc: Build debug binary
    cmds:
      - cargo build
    sources:
      - src/**/*.rs
      - Cargo.toml
    generates:
      - "{{.DEBUG_BIN}}"

  build-release:
    desc: Build release binary (optimized)
    cmds:
      - cargo build --release
    sources:
      - src/**/*.rs
      - Cargo.toml
    generates:
      - "{{.RELEASE_BIN}}"

  clean:
    desc: Clean build artifacts
    cmds:
      - cargo clean
      - rm -rf {{.TARGET_DIR}}

  # ============================================
  # Test Tasks
  # ============================================

  test:
    desc: Run all tests
    cmds:
      - cargo test

  test-verbose:
    desc: Run tests with verbose output
    cmds:
      - cargo test -- --nocapture

  test-watch:
    desc: Run tests on file change (requires cargo-watch)
    cmds:
      - cargo watch -x test

  # ============================================
  # Run Tasks
  # ============================================

  run:
    desc: Run in debug mode (default config)
    deps: [build]
    cmds:
      - "{{.DEBUG_BIN}}"

  run-release:
    desc: Run release binary
    deps: [build-release]
    cmds:
      - "{{.RELEASE_BIN}}"

  run-sa:
    desc: Run as South America POP
    deps: [build]
    env:
      EDGEPROXY_REGION: sa
      EDGEPROXY_LISTEN_ADDR: "0.0.0.0:8080"
    cmds:
      - "{{.DEBUG_BIN}}"

  run-us:
    desc: Run as US POP
    deps: [build]
    env:
      EDGEPROXY_REGION: us
      EDGEPROXY_LISTEN_ADDR: "0.0.0.0:8081"
    cmds:
      - "{{.DEBUG_BIN}}"

  run-eu:
    desc: Run as EU POP
    deps: [build]
    env:
      EDGEPROXY_REGION: eu
      EDGEPROXY_LISTEN_ADDR: "0.0.0.0:8082"
    cmds:
      - "{{.DEBUG_BIN}}"

  # ============================================
  # Database Tasks
  # ============================================

  db-init:
    desc: Initialize routing.db from schema
    cmds:
      - rm -f routing.db
      - sqlite3 routing.db < sql/create_routing_db.sql
      - echo "Database initialized with sample backends"

  db-show:
    desc: Show all backends in routing.db
    cmds:
      - sqlite3 -header -column routing.db "SELECT * FROM backends"

  db-healthy:
    desc: Show only healthy backends
    cmds:
      - sqlite3 -header -column routing.db "SELECT id, region, wg_ip, port FROM backends WHERE healthy = 1 AND (deleted IS NULL OR deleted = 0)"

  # ============================================
  # Node Management Tasks
  # ============================================

  node-add:
    desc: "Add a new node. Usage: task node-add -- ID REGION WG_IP [PORT] [WEIGHT]"
    cmds:
      - |
        if [ -z "{{.CLI_ARGS}}" ]; then
          echo "Usage: task node-add -- <id> <region> <wg_ip> [port] [weight]"
          echo ""
          echo "Examples:"
          echo "  task node-add -- sa-node-2 sa 10.50.1.2"
          echo "  task node-add -- us-node-2 us 10.50.2.2 8080"
          echo "  task node-add -- eu-node-2 eu 10.50.3.2 8080 2"
          exit 1
        fi

        ID=$(echo "{{.CLI_ARGS}}" | awk '{print $1}')
        REGION=$(echo "{{.CLI_ARGS}}" | awk '{print $2}')
        WG_IP=$(echo "{{.CLI_ARGS}}" | awk '{print $3}')
        PORT=$(echo "{{.CLI_ARGS}}" | awk '{print $4}')
        WEIGHT=$(echo "{{.CLI_ARGS}}" | awk '{print $5}')

        PORT=${PORT:-8080}
        WEIGHT=${WEIGHT:-1}

        sqlite3 routing.db "INSERT INTO backends (id, app, region, wg_ip, port, healthy, weight, soft_limit, hard_limit) VALUES ('$ID', 'myapp', '$REGION', '$WG_IP', $PORT, 1, $WEIGHT, 100, 200)"
        echo "Node added: $ID (region=$REGION, wg_ip=$WG_IP, port=$PORT, weight=$WEIGHT)"
        task db-show

  node-remove:
    desc: "Remove a node (soft delete). Usage: task node-remove -- ID"
    cmds:
      - |
        if [ -z "{{.CLI_ARGS}}" ]; then
          echo "Usage: task node-remove -- <id>"
          echo "Example: task node-remove -- sa-node-2"
          exit 1
        fi

        ID="{{.CLI_ARGS}}"
        sqlite3 routing.db "UPDATE backends SET deleted = 1 WHERE id = '$ID'"
        echo "Node removed (soft delete): $ID"
        task db-show

  node-delete:
    desc: "Permanently delete a node. Usage: task node-delete -- ID"
    cmds:
      - |
        if [ -z "{{.CLI_ARGS}}" ]; then
          echo "Usage: task node-delete -- <id>"
          echo "Example: task node-delete -- sa-node-2"
          exit 1
        fi

        ID="{{.CLI_ARGS}}"
        sqlite3 routing.db "DELETE FROM backends WHERE id = '$ID'"
        echo "Node permanently deleted: $ID"
        task db-show

  node-enable:
    desc: "Enable a node (set healthy=1). Usage: task node-enable -- ID"
    cmds:
      - |
        if [ -z "{{.CLI_ARGS}}" ]; then
          echo "Usage: task node-enable -- <id>"
          exit 1
        fi

        ID="{{.CLI_ARGS}}"
        sqlite3 routing.db "UPDATE backends SET healthy = 1, deleted = 0 WHERE id = '$ID'"
        echo "Node enabled: $ID"

  node-disable:
    desc: "Disable a node (set healthy=0). Usage: task node-disable -- ID"
    cmds:
      - |
        if [ -z "{{.CLI_ARGS}}" ]; then
          echo "Usage: task node-disable -- <id>"
          exit 1
        fi

        ID="{{.CLI_ARGS}}"
        sqlite3 routing.db "UPDATE backends SET healthy = 0 WHERE id = '$ID'"
        echo "Node disabled: $ID"

  node-weight:
    desc: "Set node weight. Usage: task node-weight -- ID WEIGHT"
    cmds:
      - |
        if [ -z "{{.CLI_ARGS}}" ]; then
          echo "Usage: task node-weight -- <id> <weight>"
          echo "Example: task node-weight -- sa-node-1 3"
          exit 1
        fi

        ID=$(echo "{{.CLI_ARGS}}" | awk '{print $1}')
        WEIGHT=$(echo "{{.CLI_ARGS}}" | awk '{print $2}')

        sqlite3 routing.db "UPDATE backends SET weight = $WEIGHT WHERE id = '$ID'"
        echo "Node weight updated: $ID -> $WEIGHT"

  node-limits:
    desc: "Set node connection limits. Usage: task node-limits -- ID SOFT_LIMIT HARD_LIMIT"
    cmds:
      - |
        if [ -z "{{.CLI_ARGS}}" ]; then
          echo "Usage: task node-limits -- <id> <soft_limit> <hard_limit>"
          echo "Example: task node-limits -- sa-node-1 50 100"
          exit 1
        fi

        ID=$(echo "{{.CLI_ARGS}}" | awk '{print $1}')
        SOFT=$(echo "{{.CLI_ARGS}}" | awk '{print $2}')
        HARD=$(echo "{{.CLI_ARGS}}" | awk '{print $3}')

        sqlite3 routing.db "UPDATE backends SET soft_limit = $SOFT, hard_limit = $HARD WHERE id = '$ID'"
        echo "Node limits updated: $ID -> soft=$SOFT, hard=$HARD"

  # ============================================
  # Development Tasks
  # ============================================

  dev:
    desc: Run with auto-reload (requires cargo-watch)
    cmds:
      - cargo watch -x run

  check:
    desc: Check code without building
    cmds:
      - cargo check

  fmt:
    desc: Format code
    cmds:
      - cargo fmt

  fmt-check:
    desc: Check code formatting
    cmds:
      - cargo fmt -- --check

  clippy:
    desc: Run clippy linter
    cmds:
      - cargo clippy -- -D warnings

  lint:
    desc: Run all linters (fmt + clippy)
    cmds:
      - task: fmt-check
      - task: clippy

  # ============================================
  # Dependencies
  # ============================================

  deps-install:
    desc: Install development dependencies
    cmds:
      - cargo install cargo-watch
      - cargo install cargo-edit
      - echo "Dev dependencies installed"

  deps-update:
    desc: Update Cargo dependencies
    cmds:
      - cargo update

  deps-outdated:
    desc: Check for outdated dependencies
    cmds:
      - cargo outdated || echo "Run cargo install cargo-outdated"

  # ============================================
  # Rust Documentation
  # ============================================

  docs:
    desc: Generate and open Rust API documentation
    cmds:
      - cargo doc --open

  docs-build:
    desc: Generate Rust API documentation
    cmds:
      - cargo doc --no-deps

  # ============================================
  # Docusaurus Documentation
  # ============================================

  docs-install:
    desc: Install documentation dependencies
    dir: docs
    cmds:
      - npm install

  docs-dev:
    desc: Start documentation dev server (English)
    dir: docs
    cmds:
      - npm run start

  docs-dev-pt:
    desc: Start documentation dev server (Portuguese)
    dir: docs
    cmds:
      - npm run start -- --locale pt-BR

  docs-build-site:
    desc: Build documentation static site
    dir: docs
    cmds:
      - npm run build

  docs-serve:
    desc: Serve built documentation locally
    dir: docs
    cmds:
      - npm run serve

  docs-write-translations:
    desc: Generate translation files
    dir: docs
    cmds:
      - npm run write-translations -- --locale pt-BR

  docs-clean:
    desc: Clean documentation build
    dir: docs
    cmds:
      - rm -rf build .docusaurus

  # ============================================
  # Utility Tasks
  # ============================================

  info:
    desc: Show build info
    cmds:
      - echo "Rust version"
      - rustc --version
      - echo ""
      - echo "Cargo version"
      - cargo --version
      - echo ""
      - echo "Target architecture"
      - rustc -vV | grep host
      - echo ""
      - echo "Binary size (if built)"
      - ls -lh {{.RELEASE_BIN}} 2>/dev/null || echo "Release binary not built yet"

  size:
    desc: Show binary size breakdown
    deps: [build-release]
    cmds:
      - cargo bloat --release -n 20 || echo "Run cargo install cargo-bloat"

  bench:
    desc: Run benchmarks
    cmds:
      - cargo bench

  # ============================================
  # Connection Test Tasks
  # ============================================

  test-conn:
    desc: Test TCP connection to local edgeProxy
    cmds:
      - nc -zv localhost 8080 || echo "edgeProxy not running on port 8080"

  test-backends:
    desc: Test connectivity to all backends
    cmds:
      - echo "Testing backend connectivity..."
      - |
        sqlite3 routing.db "SELECT wg_ip, port FROM backends WHERE healthy = 1" | while IFS='|' read ip port; do
          echo -n "Testing $ip:$port... "
          nc -zv -w 2 $ip $port 2>&1 | grep -q "succeeded" && echo "OK" || echo "FAIL"
        done

  # ============================================
  # Local Environment Simulation
  # ============================================

  local-env:
    desc: Start local test environment (3 backends + proxy)
    deps: [build-release]
    cmds:
      - ./tests/start_local_env.sh

  local-test:
    desc: Run routing tests against local environment
    cmds:
      - ./tests/test_routing.sh

  local-db-setup:
    desc: Configure routing.db for local testing (localhost backends)
    cmds:
      - |
        sqlite3 routing.db << 'EOF'
        DELETE FROM backends;
        INSERT INTO backends (id, app, region, wg_ip, port, healthy, weight, soft_limit, hard_limit)
        VALUES
          ('sa-node-1', 'myapp', 'sa', '127.0.0.1', 9001, 1, 1, 100, 200),
          ('us-node-1', 'myapp', 'us', '127.0.0.1', 9002, 1, 1, 100, 200),
          ('eu-node-1', 'myapp', 'eu', '127.0.0.1', 9003, 1, 1, 100, 200);
        EOF
      - task: db-show

  local-db-reset:
    desc: Reset routing.db to original WireGuard IPs
    cmds:
      - task: db-init

  # ============================================
  # Multi-Region Simulation
  # ============================================

  sim:
    desc: Start full multi-region simulation (3 POPs + 9 backends)
    deps: [build-release]
    cmds:
      - ./tests/simulate_multi_region.sh

  sim-test:
    desc: Run multi-region routing tests
    cmds:
      - ./tests/test_multi_region.sh

  # ============================================
  # Docker
  # ============================================

  docker-build:
    desc: Build Docker images
    cmds:
      - docker compose build

  docker-up:
    desc: Start Docker environment (3 POPs + 9 backends)
    cmds:
      - docker compose up -d
      - echo ""
      - echo "edgeProxy Docker environment started"
      - echo ""
      - echo "POPs available at:"
      - echo "  SA POP - localhost:8080"
      - echo "  US POP - localhost:8081"
      - echo "  EU POP - localhost:8082"
      - echo ""
      - echo "Run 'task docker-test' to execute tests"

  docker-down:
    desc: Stop Docker environment
    cmds:
      - docker compose down

  docker-logs:
    desc: Show Docker logs
    cmds:
      - docker compose logs -f

  docker-test:
    desc: Run tests inside Docker
    cmds:
      - docker compose run --rm test-runner

  docker-test-host:
    desc: Run tests from host against Docker containers
    cmds:
      - |
        echo "Testing edgeProxy in Docker..."
        echo ""
        echo "SA POP (localhost:8080):"
        echo "" | nc -w 2 localhost 8080 | head -1
        echo ""
        echo "US POP (localhost:8081):"
        echo "" | nc -w 2 localhost 8081 | head -1
        echo ""
        echo "EU POP (localhost:8082):"
        echo "" | nc -w 2 localhost 8082 | head -1

  docker-clean:
    desc: Remove Docker images and volumes
    cmds:
      - docker compose down -v --rmi local
