version: '3'

tasks:
  default:
    desc: Build and serve with all locales (EN + PT-BR)
    cmds:
      - task: serve

  dev:
    desc: Start development server (hot reload, single locale EN only)
    cmds:
      - npm run start
    silent: false

  build:
    desc: Build static site for all locales (EN + PT-BR)
    cmds:
      - npm run clear
      - npm run build
    silent: false

  serve:
    desc: Build and serve with all locales (EN + PT-BR) - USE THIS FOR i18n
    deps: [build]
    cmds:
      - npm run serve
    silent: false

  clean:
    desc: Clean cache and build artifacts
    cmds:
      - rm -rf .docusaurus build node_modules/.cache
    silent: false

  rebuild:
    desc: Clean, build and serve with all locales
    cmds:
      - task: clean
      - task: serve
