version: '3'

tasks:
  dev:
    desc: Start development server (hot reload, single locale)
    cmds:
      - npm run start
    silent: false

  build:
    desc: Build static site for all locales (EN + PT-BR)
    cmds:
      - rm -rf .docusaurus build
      - npm run build
    silent: false

  serve:
    desc: Serve built site with all locales (EN + PT-BR)
    deps: [build]
    cmds:
      - npm run serve
    silent: false

  clean:
    desc: Clean cache and build artifacts
    cmds:
      - rm -rf .docusaurus build node_modules/.cache
    silent: false

  rebuild:
    desc: Clean, build and serve
    cmds:
      - task: clean
      - task: serve
